apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
      - name: nexus
        image: customcontainers101.azurecr.io/custom-nexus:v1
        ports:
        - containerPort: 8081

---

apiVersion: v1
kind: Service
metadata:
  name: nexus-service
spec:
  type: LoadBalancer
  ports:
    - port: 8081
  selector:
    app: nexus