# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: jenkins-pvc
# spec:
#   accessModes:
#     - ReadWriteOnce  # Use this if the volume is mounted by a single node
#   resources:
#     requests:
#       storage: 10Gi  # Specify the size of the volume you need

# ---

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: jenkins
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: jenkins
#   template:
#     metadata:
#       labels:
#         app: jenkins
#     spec:
#       containers:
#       - name: jenkins
#         image: customcontainers101.azurecr.io/custom-jenkins:v1  # Use the ACR image
#         imagePullPolicy: Always
#         ports:
#         - containerPort: 8080
#         - containerPort: 50000
#         volumeMounts:
#         - name: jenkins-home
#           mountPath: /var/jenkins_home
#       volumes:
#       - name: jenkins-home
#         persistentVolumeClaim:
#           claimName: jenkins-pvc  # Use the PVC created above

# ---

# apiVersion: v1
# kind: Service
# metadata:
#   name: jenkins-service
# spec:
#   type: LoadBalancer
#   ports:
#     - port: 8080
#   selector:
#     app: jenkins

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: customcontainers101.azurecr.io/custom-jenkins:v1
        ports:
        - containerPort: 8080
        - containerPort: 50000
      #   volumeMounts:
      #   - name: jenkins-home
      #     mountPath: /var/jenkins_home
      # # volumes:
      # - name: jenkins-home
      #   # emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
  selector:
    app: jenkins
